# Manual steps required!
# - Install the aur ansible module:
#   `git clone https://github.com/kewlfft/ansible-aur.git ~/.ansible/plugins/modules/aur`
# - Consider installing an aur helper such as yay:
#   https://wiki.archlinux.org/index.php/AUR_helpers
#   https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_and_upgrading_packages

- user:
    name: aur_builder
    group: wheel
- lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- aur:
    name: snapcast
    # use: yay
    state: present
  become: yes
  become_user: aur_builder

- name: install mpd & mpc
  pacman:
    update_cache: true
    name:
      - mpd
        mpc

- include: mount_shares.yml

- include: radio.yml

# TODO: change this to music when/if this replaces the old server.
- name: set server/hostname
  command: hostnamectl set-hostname nina

- name: give mpd dir permissions
  file:
    path: /var/lib/mpd
    owner: mpd

- name: create the music dir
  file:
    path: /var/lib/mpd/music
    state: directory

- name: link the shares into the music dir
  ignore_errors: true
  file:
    src: /mnt/{{ item }}
    dest: /var/lib/mpd/music/{{ item }}
    owner: mpd
    group: mpd
    state: link
  with_items:
    - music
    - playlists
    - podcasts
    - records

- name: configure mpd
  copy:
    src: mpd.conf
    dest: /etc/mpd.conf
    mode: 0644
    backup: true

- name: enable mpd daemon
  service:
    name: mpd
    enabled: yes

- name: start mpd daemon
  service:
    name: mpd
    state: started

- name: enable snapserver daemon
  service:
    name: snapserver
    enabled: yes

- name: start snapserver daemon
  service:
    name: snapserver
    state: started
