# Important manual steps required:
#
# pacman -Syu
# pacman -S python2
# DO NOT LOG OUT FROM root OR YOU WILL GET LOCKED OUT!
# run this playbook `ansible-playbook -i inventory --ask-pass base_arch.yml`
# passwd joe
# reboot
# if you logged out from root. Stick the sd card in anouther machine and edit
# /etc/ssh/sshd_config to comment out `PasswordAuthentication no`
#
# If root login is already disabled in the base image, you can temporarily
# enable it with:
# vi /etc/ssh/sshd_config
# PermitRootLogin yes
# PasswordAuthentication yes
# systemctl restart sshd

# Other manual steps required!
# - Install the aur ansible module:
#   `git clone https://github.com/kewlfft/ansible-aur.git ~/.ansible/plugins/modules/aur`

# Install this aur helper. Without this, the aur installation module can fail
# if not all deps are met. This handles the deps silently, much easier.
# https://wiki.archlinux.org/index.php/AUR_helpers
# https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_and_upgrading_packages
# git clone https://aur.archlinux.org/yay.git
# cd yay
# makepkg -si

- name: set the timezone
  command: timedatectl set-timezone Europe/London

- name: install necessary or useful packages
  pacman:
    # update_cache: true
    state: present
    name:
      - sudo
      - vim
      - wget
      - tree
      - base-devel
      - packer
      - git
      - python
      - go

- name: configure sudo
  lineinfile:
    dest: /etc/sudoers
    regexp: "joe ALL"
    line: "joe ALL=(ALL) ALL"
    state: present
    validate: 'visudo -cf %s'

- name: Add joe user
  user: name=joe groups=users shell=/bin/bash

- name: Give joe his authorized keys file
  authorized_key:
    user: joe
    key: "{{ lookup('file', '/Users/joe/.ssh/id_ed25519.pub') }}"

- name: Remove ability for root user to login over ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication"
    insertafter: "^#PasswordAuthentication"
    line: "PasswordAuthentication no"

- name: Add a user for running aur installs
  user:
    name: aur_builder
    group: wheel

- name: configure the aur installing user to not require a password for pacman
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
