# NOTE: superseded by music_client_snapcast (using snapcast instead of
# pulseaudio).

# usage: ansible-playbook -i inventory -K music_client_pulse.yml

- hosts: music_clients
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/env python2"
  roles:
    - music_client_pulse
