# usage: ansible-playbook -i inventory -K music_server_nina.yml --ask-vault-pass

- hosts: music_servers_nina
  become: true
  vars:
  vars_files: ["group_vars/airbrake"]
  tasks:
  roles:
    - music_server_nina
