# usage: ansible-playbook -i inventory -K music_server_pulse.yml --ask-vault-pass

- hosts: music_servers
  become: true
  vars:
  vars_files: ["group_vars/airbrake"]
  tasks:
  roles:
    - music_server_pulse
    - mpdscribble
    - mothership
    - flashlight
