- name: create the radio playlist dir
  file:
    path: /var/lib/mpd/music/radio
    state: directory
    owner: mpd

- name: copy the radio playlist files
  copy:
    src: "{{ item }}"
    dest: /var/lib/mpd/music/radio
    mode: 0644
  with_items:
    - "Worldwide FM.m3u"
    - "BBC 6 Music.m3u"
    - "BBC Radio 1.m3u"
    - "BBC Radio 2.m3u"
    - "BBC Radio 3.m3u"
    - "BBC Radio 4.m3u"
    - "BBC Radio 4 Extra.m3u"
    - "BBC Radio 5 Live.m3u"
    - "BBC Radio Cumbria.m3u"
    - "Radio Paradise (main).m3u"
    - "Radio Paradise (mellow).m3u"
    - "Radio Paradise (rock).m3u"
    - "Radio Paradise (world).m3u"
