- name: create the radio playlist dir
  file:
    path: /var/lib/mpd/music/radio
    state: directory
    owner: mpd

- name: copy the Worldwide FM radio file
  copy:
    src: Worldwide FM.m3u
    dest: /var/lib/mpd/music/radio
    mode: 0644

- name: copy the Radio Paradise files
  copy:
    src: "{{ item }}"
    dest: /var/lib/mpd/music/radio
    mode: 0644
  with_items:
    - "Radio Paradise (main).m3u"
    - "Radio Paradise (mellow).m3u"
    - "Radio Paradise (rock).m3u"
    - "Radio Paradise (world).m3u"

- name: copy bbc radios script
  copy:
    src: bbc.sh
    dest: /opt/bbc.sh
    mode: 0755

- name: create bbc radio systemd service
  copy:
    src: bbc.service
    dest: /usr/lib/systemd/system/bbc.service
    mode: 0644

- name: create bbc radio systemd timer
  copy:
    src: bbc.timer
    dest: /usr/lib/systemd/system/bbc.timer
    mode: 0744

- name: start the bbc radio playlist timer
  command: systemctl start bbc.timer

- name: enable the bbc radio playlist timer
  command: systemctl enable bbc.timer

- name: run bbc.sh now
  shell: /opt/bbc.sh
