- name: install mpdscribble
  apt: name=mpdscribble update_cache=true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install binutils
  pacman: name=binutils
  when: ansible_distribution == 'Archlinux'

- name: install mpdscribble
  aur:
    name: mpdscribble
    state: present
  become: yes
  become_user: aur_builder

- name: Ensure group "mpdscribble" exists
  group:
    name: mpdscribble
    state: present

- name: Ensure user "mpdscribble" exists
  user:
    name: mpdscribble
    groups: mpdscribble
    append: false
    shell: /usr/bin/nologin
    create_home: false

- name: configure mpdscribble with last.fm credentials
  template: >
    src=mpdscribble.conf dest=/etc/mpdscribble.conf
    backup=yes mode=0640

- name: configure mpdscribble daemon
  template: >
    src=mpdscribble.service dest=/usr/lib/systemd/system/mpdscribble.service
    mode=0644

- name: enable mpdscribble daemon
  service:
    name: mpdscribble
    enabled: yes

- name: restart mpdscribble daemon
  service:
    name: mpdscribble
    state: restarted
