- name: install packages
  pacman: name={{ item }}
  with_items:
    - alsa-utils
    - linux-raspberrypi
    - linux-api-headers
    - kmod
    - linux-firmware
    - raspberrypi-firmware-bootloader
    - raspberrypi-firmware-bootloader-x
    - raspberrypi-firmware-tools

- name: configure modules
  copy: >
    src=raspberrypi.conf
    dest=/etc/modules-load.d/raspberrypi.conf
    mode=0644
    backup=true
