- name: install mpd & mpc
  pacman: name={{ item }} update_cache=true
  with_items:
    - mpd
    - mpc

# Opting for doing this manually from now on, as different versions of Pis,
# DAC boards, and Linux versions mean it's quicker just to follow the relevant
# guide. See https://www.hifiberry.com/guides/
# - include: hifiberry.yml

- include: mount_shares.yml

- include: radio.yml

- name: set server/hostname
  command: hostnamectl set-hostname music

- name: give mpd dir permissions
  file: path=/var/lib/mpd owner=mpd

- name: create the music dir
  file: path=/var/lib/mpd/music state=directory

- name: link the shares into the music dir
  file: src=/mnt/{{ item }} dest=/var/lib/mpd/music/{{ item }} owner=mpd group=mpd state=link
  with_items:
    - music
    - playlists
    - podcasts
    - records

- name: configure mpd
  copy: src=mpd.conf dest=/etc/mpd.conf mode=0644 backup=true

- name: enable mpd daemon
  command: systemctl enable mpd
  when: ansible_distribution == 'Archlinux'

- name: start mpd
  service: name=mpd state=started
