- name: install samba client
  pacman: name=cifs-utils

- name: create the mount dirs
  file: path=/mnt/{{ item }} state=directory owner=mpd
  # errors occcur if the share is already mounted
  ignore_errors: true
  with_items:
    - music
    - playlists
    - podcasts
    - records

- name: create fstab mount entry for nas music
  # command: mount -t cifs //hostname/music /mnt/music -o user={{ nas.username }},password={{ nas.password }}
  lineinfile: >
    backup=true
    dest=/etc/fstab
    line="//{{ nas.host }}/{{ item }} /mnt/{{ item }} cifs vers=1.0,username={{ nas.username }},password={{ nas.password }},x-systemd.automount 0 0"
  with_items:
    - music
    - podcasts
    - records

- name: create writeable fstab mount entry for nas playlists
  lineinfile: >
    backup=true
    dest=/etc/fstab
    line="//{{ nas.host }}/{{ item }} /mnt/{{ item }} cifs vers=1.0,username={{ nas.username }},password={{ nas.password }},rw,file_mode=0777,dir_mode=0777,x-systemd.automount 0 0"
  with_items:
    - playlists

- name: mount the shares
  # errors occcur if the share is already mounted
  ignore_errors: true
  command: mount /mnt/{{ item }}
  with_items:
    - music
    - playlists
    - podcasts
    - records
